# harness.io/skip-file-for-deploy
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load
  name: load2
spec:
  containers:
  - env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: accesskey
          name: mysecret
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          key: accountname
          name: mysecret
    envFrom:
      - configMapRef:
          name: env-map
    image: appddemo/adcapital-load
    name: adcapitalload
    resources: {}
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: load
  name: load
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: load
status:
  loadBalancer: {}
